### ISSUE TITLE
Feature: Add "update playlist" API

### ISSUE THREAD

**Issue by eamonn-zh** [scp756-221/term-project-seg_fault#5]
The "update playlist" RESTful API (PUT) should be separated into two methods: 
1. add a new song into an existing playlist
2. delete a song from an existing playlist
Both methods take as input a song id and a playlist id, then update an existing playlist. It should return a proper and meaningful error message when the playlist does not exist.

**Comment by SemiXQ** [comment]
Feature added.
Update func for client is implemented in ci/v2/playlist.py
Update func for server is implemented in s3/app.py
